<template>
    <div>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="200" height="200" style="shape-rendering: auto; display: block; background: transparent;" xmlns:xlink="http://www.w3.org/1999/xlink"><g><g transform="translate(77,50)">
<g transform="rotate(0)">
<circle fill-opacity="1" fill="#b7bbc7" r="6" cy="0" cx="0">
  <animateTransform repeatCount="indefinite" dur="1s" keyTimes="0;1" values="0.16 0.16;1 1" begin="-0.8s" type="scale" attributeName="transform"></animateTransform>
  <animate begin="-0.8s" values="1;0" repeatCount="indefinite" dur="1s" keyTimes="0;1" attributeName="fill-opacity"></animate>
</circle>
</g>
        </g><g transform="translate(58.34345884812358,75.67852593996915)">
        <g transform="rotate(72)">
        <circle fill-opacity="0.8" fill="#b7bbc7" r="6" cy="0" cx="0">
        <animateTransform repeatCount="indefinite" dur="1s" keyTimes="0;1" values="0.16 0.16;1 1" begin="-0.6s" type="scale" attributeName="transform"></animateTransform>
        <animate begin="-0.6s" values="1;0" repeatCount="indefinite" dur="1s" keyTimes="0;1" attributeName="fill-opacity"></animate>
        </circle>
        </g>
        </g><g transform="translate(28.15654115187642,65.87020181189678)">
        <g transform="rotate(144)">
        <circle fill-opacity="0.6" fill="#b7bbc7" r="6" cy="0" cx="0">
        <animateTransform repeatCount="indefinite" dur="1s" keyTimes="0;1" values="0.16 0.16;1 1" begin="-0.4s" type="scale" attributeName="transform"></animateTransform>
        <animate begin="-0.4s" values="1;0" repeatCount="indefinite" dur="1s" keyTimes="0;1" attributeName="fill-opacity"></animate>
        </circle>
        </g>
        </g><g transform="translate(28.156541151876414,34.12979818810323)">
        <g transform="rotate(216)">
        <circle fill-opacity="0.4" fill="#b7bbc7" r="6" cy="0" cx="0">
        <animateTransform repeatCount="indefinite" dur="1s" keyTimes="0;1" values="0.16 0.16;1 1" begin="-0.2s" type="scale" attributeName="transform"></animateTransform>
        <animate begin="-0.2s" values="1;0" repeatCount="indefinite" dur="1s" keyTimes="0;1" attributeName="fill-opacity"></animate>
        </circle>
        </g>
        </g><g transform="translate(58.343458848123575,24.32147406003085)">
        <g transform="rotate(288)">
        <circle fill-opacity="0.2" fill="#b7bbc7" r="6" cy="0" cx="0">
        <animateTransform repeatCount="indefinite" dur="1s" keyTimes="0;1" values="0.16 0.16;1 1" begin="0s" type="scale" attributeName="transform"></animateTransform>
        <animate begin="0s" values="1;0" repeatCount="indefinite" dur="1s" keyTimes="0;1" attributeName="fill-opacity"></animate>
        </circle>
        </g>
        </g><g></g></g><!-- [ldio] generated by https://loading.io --></svg>
    </div>
</template>