<template>
   <div >
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="21" height="21" style="shape-rendering: auto; display: block; background: transparent;" xmlns:xlink="http://www.w3.org/1999/xlink"><g><circle stroke-linecap="round" fill="none" stroke-dasharray="40.840704496667314 40.840704496667314" stroke="#dad0d0" stroke-width="10" r="26" cy="50" cx="50">
        <animateTransform values="0 50 50;360 50 50" keyTimes="0;1" repeatCount="indefinite" dur="1s" type="rotate" attributeName="transform"></animateTransform>
      </circle>
      <circle stroke-linecap="round" fill="none" stroke-dashoffset="23.561944901923447" stroke-dasharray="23.561944901923447 23.561944901923447" stroke="#f8b26a" stroke-width="10" r="15" cy="50" cx="50">
        <animateTransform values="0 50 50;-360 50 50" keyTimes="0;1" repeatCount="indefinite" dur="1s" type="rotate" attributeName="transform"></animateTransform>
      </circle><g></g></g><!-- [ldio] generated by https://loading.io --></svg>

   </div>
</template>